# Generated by Django 3.2.6 on 2021-08-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemarking', '0004_auto_20210821_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
